backup

diff --git a/meta-builder/config/samples/blackduck_runtime_objects.yaml b/meta-builder/config/samples/blackduck_runtime_objects.yaml
--- a/meta-builder/config/samples/blackduck_runtime_objects.yaml
+++ b/meta-builder/config/samples/blackduck_runtime_objects.yaml
@@ -1320,3 +1320,119 @@ metadata:
   namespace: blackduck
 type: Opaque
 
+---
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: postgres-init-config
+  namespace: blackduck
+data:
+  init.sh: |-
+    #!/bin/bash
+
+    if [[ $# -ne 1 ]]; then
+      echo "hostname must be specified"
+      exit 1
+    fi
+
+    if [[ `psql -h tesdt-blackduck-postgres -U postgres -c "SELECT datname FROM pg_catalog.pg_database WHERE datname='bds_hub';" --tuples-only | wc -l` -eq 1 ]]; then
+      echo "bds_hub is missing. Initializing the database..."
+      psql -h $HUB_POSTGRES_HOST -U postgres -f /tmp/postgres-init/init.sql
+    fi
+  init.sql: |-
+    CREATE USER blackduck_user WITH NOCREATEDB NOSUPERUSER NOREPLICATION NOBYPASSRLS PASSWORD '$HUB_POSTGRES_USER_PASSWORD_FILE';
+    CREATE USER blackduck_reporter;
+    CREATE DATABASE bds_hub owner blackduck TEMPLATE template0 ENCODING SQL_ASCII;
+    CREATE DATABASE bds_hub_report owner blackduck TEMPLATE template0 ENCODING SQL_ASCII;
+    CREATE DATABASE bdio owner blackduck TEMPLATE template0 ENCODING SQL_ASCII;
+    ALTER USER blackduck WITH NOCREATEDB SUPERUSER NOREPLICATION BYPASSRLS PASSWORD '$HUB_POSTGRES_ADMIN_PASSWORD_FILE';
+    \c bds_hub
+    CREATE EXTENSION pgcrypto;
+    CREATE SCHEMA st AUTHORIZATION blackduck;
+    GRANT USAGE ON SCHEMA st TO blackduck_user;
+    GRANT SELECT, INSERT, UPDATE, TRUNCATE, DELETE, REFERENCES ON ALL TABLES IN SCHEMA st TO blackduck_user;
+    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA st to blackduck_user;
+    ALTER DEFAULT PRIVILEGES IN SCHEMA st GRANT SELECT, INSERT, UPDATE, TRUNCATE, DELETE, REFERENCES ON TABLES TO blackduck_user;
+    ALTER DEFAULT PRIVILEGES IN SCHEMA st GRANT ALL PRIVILEGES ON SEQUENCES TO blackduck_user;
+    ALTER DATABASE bds_hub SET standard_conforming_strings TO OFF;
+    \c bds_hub_report
+    GRANT SELECT ON ALL TABLES IN SCHEMA public TO blackduck_reporter;
+    ALTER DEFAULT PRIVILEGES FOR ROLE blackduck IN SCHEMA public GRANT SELECT ON TABLES TO blackduck_reporter;
+    GRANT SELECT, INSERT, UPDATE, TRUNCATE, DELETE, REFERENCES ON ALL TABLES IN SCHEMA public TO blackduck_user;
+    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public to blackduck_user;
+    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, TRUNCATE, DELETE, REFERENCES ON TABLES TO blackduck_user;
+    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO blackduck_user;
+    ALTER DATABASE bds_hub_report SET standard_conforming_strings TO OFF;
+    \c bdio
+    GRANT ALL PRIVILEGES ON DATABASE bdio TO blackduck_user;
+    ALTER DATABASE bdio SET standard_conforming_strings TO ON;
+    ALTER SYSTEM SET autovacuum TO 'on';
+    ALTER SYSTEM SET autovacuum_max_workers TO '20';
+    ALTER SYSTEM SET autovacuum_vacuum_cost_limit TO '2000';
+    ALTER SYSTEM SET autovacuum_vacuum_cost_delay TO '10ms';
+    ALTER SYSTEM SET checkpoint_completion_target TO '0.8';
+    ALTER SYSTEM SET max_wal_size TO '8GB';
+    ALTER SYSTEM SET checkpoint_timeout TO '30min';
+    ALTER SYSTEM SET constraint_exclusion TO 'partition';
+    ALTER SYSTEM SET default_statistics_target TO '100';
+    ALTER SYSTEM SET effective_cache_size TO '256MB';
+    ALTER SYSTEM SET escape_string_warning TO 'off';
+    ALTER SYSTEM SET log_destination TO 'stderr';
+    ALTER SYSTEM SET log_directory TO 'pg_log';
+    ALTER SYSTEM SET log_filename TO 'postgresql_%a.log';
+    ALTER SYSTEM SET log_line_prefix TO '%m %p ';
+    ALTER SYSTEM SET log_rotation_age TO '1440';
+    ALTER SYSTEM SET log_truncate_on_rotation TO 'on';
+    ALTER SYSTEM SET logging_collector TO 'on';
+    ALTER SYSTEM SET maintenance_work_mem TO '32MB';
+    ALTER SYSTEM SET max_connections TO '300';
+    ALTER SYSTEM SET max_locks_per_transaction TO '256';
+    ALTER SYSTEM SET random_page_cost TO '4.0';
+    ALTER SYSTEM SET standard_conforming_strings TO 'off';
+    ALTER SYSTEM SET temp_buffers TO '16MB';
+    ALTER SYSTEM SET work_mem TO '32MB';
+    SELECT pg_reload_conf();
+
+---
+apiVersion: batch/v1
+kind: Job
+metadata:
+  name: blackduck-init-postgres
+  namespace: blackduck
+spec:
+  template:
+    spec:
+      volumes:
+        - name: postgres-init
+          configMap:
+            defaultMode: 0777
+            name: postgres-init-config
+      containers:
+        - name: postgres-init
+          image: registry.access.redhat.com/rhscl/postgresql-96-rhel7:1
+          command: ["/bin/bash"]
+          args: ["-c", "sleep 600000000; psql -h postgres -U postgres -f /tmp/postgres-init/init.sql "]
+          volumeMounts:
+            - mountPath: /tmp/postgres-init
+              name: postgres-init
+          envFrom:
+            - configMapRef:
+                name: blackduck-db-config
+          env:
+            - name: PGPASSWORD
+              valueFrom:
+                secretKeyRef:
+                  key: HUB_POSTGRES_POSTGRES_PASSWORD_FILE
+                  name: blackduck-db-creds
+            - name: HUB_POSTGRES_USER_PASSWORD_FILE
+              valueFrom:
+                secretKeyRef:
+                  key: HUB_POSTGRES_USER_PASSWORD_FILE
+                  name: blackduck-db-creds
+            - name: HUB_POSTGRES_ADMIN_PASSWORD_FILE
+              valueFrom:
+                secretKeyRef:
+                  key: HUB_POSTGRES_ADMIN_PASSWORD_FILE
+                  name: blackduck-db-creds
+      restartPolicy: Never
+  backoffLimit: 4
